### ISSUE TITLE
Audio length 

### ISSUE THREAD

**Issue by ovninosa** [ALIZE-Speaker-Recognition/android-alize-demo#2]
Hello,

I recently use the app, run OK. I can train my voice speaking between 5, 10 and 20 seconds.
The response is always negative over test (verification) and identification.

There is a good length for the training, verification and identification?
Something like:

Training: at least 20 seconds
Verification: at least 5 seconds
Identification: at least 10 seconds.

Thanks

**Comment by jfb84** [comment]
HiDid you look at the scores ?The default decision threshold is 0 I think.Not good (at least without score norm). Easy to fixJfEnvoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : ovninosa <notifications@github.com> Date : 15/11/2018  21:12  (GMT+01:00) À : ALIZE-Speaker-Recognition/android-alize-demo <android-alize-demo@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [ALIZE-Speaker-Recognition/android-alize-demo] Audio length  (#2) Hello,
I recently use the app, run OK. I can train my voice speaking between 5, 10 and 20 seconds.
The response is always negative over test (verification) and identification.
There is a good length for the training, verification and identification?
Something like:
Training: at least 20 seconds
Verification: at least 5 seconds
Identification: at least 10 seconds.
Thanks

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ALIZE-Speaker-Recognition/android-alize-demo","title":"ALIZE-Speaker-Recognition/android-alize-demo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ALIZE-Speaker-Recognition/android-alize-demo"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Audio length  (#2)"}],"action":{"name":"View Issue","url":"https://github.com/ALIZE-Speaker-Recognition/android-alize-demo/issues/2"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ALIZE-Speaker-Recognition/android-alize-demo/issues/2",
"url": "https://github.com/ALIZE-Speaker-Recognition/android-alize-demo/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Audio length  (#2)",
"sections": [
{
"text": "",
"activityTitle": "**ovninosa**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ovninosa",
"facts": [
{
"name": "Repository: ",
"value": "ALIZE-Speaker-Recognition/android-alize-demo"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ALIZE-Speaker-Recognition/android-alize-demo\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ALIZE-Speaker-Recognition/android-alize-demo\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ALIZE-Speaker-Recognition/android-alize-demo/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 411654148\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by YYLee92** [comment]
Hi ,

I manage to get positive scoring with speaker model trained with my own voice (10 seconds) against verification (5 seconds). 
Issue I facing is the app will crash usually after N time of audio recording activity, and all the trained speaker model is gone after the app crash and not able to get it back when I rerun the app.

Regards,
YiYang

**Comment by ovninosa** [comment]
Over my test I tried with audios from 5 seconds to 30 seconds on enrolment then 5 seconds and 10 seconds to test, always the threshold was negative.
I did it wrong? or what I miss something?

THanks

**Comment by Ferrone84** [comment]
Hello everyone,
First of all, you can now set the recognition threshold as you like in the settings of the application.
Secondly, I advise you to have a longer record to improve the results. 
Also, if you still are experiencing problems with the loss of the speakers models, you can save them in the settings.

Best regards,
Nicolas.
